// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
   // Dividing 8" wheel circumference by encoder counts per revolution of TalonSRX
   public static final double countsPerInch = 4096 / (8 * Math.PI);

   // Kp for various proportional controllers
   public static final double autoTurnKp = 0.05;
   public static final double autoStraightTurnKp = 0.005;
   public static final double autoStaightKp = 0.001;
   public static final double autoDriveToPointKp = 4.1;

   // Joystick ratios
   public static final double fineTurnRatio = 0.5;

   // Indexer powers
   public static final double intakePwr = 0.9;
   public static final double indexerPwr = 0.5;

   // Shooter powers
   public static final double lowGoalPwr = 0.325;
   public static final double launchpadPwr = 0.95;
}

