// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.Constants;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.I2C.Port;
// import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import com.revrobotics.CANSparkMax;
import com.revrobotics.ColorSensorV3;
import com.revrobotics.CANSparkMaxLowLevel.MotorType;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


public class IndexerSys extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private CANSparkMax intakeMtr;
    private WPI_TalonSRX feedMtr;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private ColorSensorV3 sensor;

    private LightsSys m_lightsSys;

    private boolean m_cargoIsGood;

    /**
     * Constructs a new IndexerSys.
     * 
     * IndexerSys contains the intake and indexer motors and the color/proximity sensor.
     * 
     * This subsystem contains methods for running the intake routine, setting the powers of the motors,
     * and stopping them.
     */
    public IndexerSys(LightsSys lightsSys) {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        intakeMtr = new CANSparkMax(8, MotorType.kBrushless);
        intakeMtr.setInverted(true);

        feedMtr = new WPI_TalonSRX(9);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        sensor = new ColorSensorV3(Port.kOnboard);

        m_lightsSys = lightsSys;
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        if(sensor.getProximity() > Constants.Sensor.indexerProxThresh) {
            if(sensor.getBlue() > 370) {
                if(DriverStation.getAlliance() == Alliance.Blue) {
                    m_cargoIsGood = false;
                }
                else {
                    m_cargoIsGood = true;
                }
                if(!m_lightsSys.isMode()) {
                    m_lightsSys.red();
                }
                // SmartDashboard.putString("cargo color", "red");
            }
            else  {
                if(DriverStation.getAlliance() == Alliance.Red) {
                    m_cargoIsGood = false;
                }
                else {
                    m_cargoIsGood = true;
                }
                if(!m_lightsSys.isMode()) {
                    m_lightsSys.blue();
                }
                // SmartDashboard.putString("cargo color", "blue");
            }
        }
        else {
            if(!m_lightsSys.isMode()) {
                m_lightsSys.green();
            }
            // SmartDashboard.putString("cargo color", "N/A");
            m_cargoIsGood = true;
        }
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    /**
     * Runs the intake unless a second cargo has pushed the first one in front of the sensor.
     */
    public void intake() {
        if(sensor.getProximity() > Constants.Sensor.indexerProxThresh) {
            intakeMtr.stopMotor();
        }
        else {
            intakeMtr.set(Constants.Power.intake);
        }
    }

    public void feed() {
        intakeMtr.set(Constants.Power.intakeToFeedRatio);
        feedMtr.set(Constants.Power.feedFeed);
    }

    /**
     * Sets the power of both motors of the indexer.
     * 
     * @param power the desired power to set the indexer to
     */
    public void set(double power) {
        if(cargoIsIn() || power > 0) {
            intakeMtr.set(power * Constants.Power.intake);
        }
        else {
            intakeMtr.set(power);
        }
        feedMtr.set(power);
    }

    /**
     * Stops both motors of the indexer.
     */
    public void stop() {
        intakeMtr.stopMotor();
        feedMtr.stopMotor();
    }

    /**
     * Checks whether the next cargo should be shot.
     * 
     * @return true if the color of the cargo in front of the sensor matches the alliance color.
     */
    public boolean cargoIsGood() {
        return m_cargoIsGood;
    }

    public boolean cargoIsIn() {
        if(sensor.getProximity() > Constants.Sensor.indexerProxThresh) {
            return true;
        }
        else {
            return false;
        }
    }

    public void operatorControl(double set, boolean runIntake) {
        if(runIntake) {
            intake();
        }
        else {
            set(set);
        }
    }

}